
services:
  postgres:
    image: postgres:15-alpine
    container_name: attrition_postgres
    environment:
      POSTGRES_USER: attrition_user
      POSTGRES_PASSWORD: attrition_DBpass001
      POSTGRES_DB: employee_attrition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: attrition_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: opeyemiskolade@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Kolade_Samuel001
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: